#!/usr/bin/env python3
"""Emit rtl/keccak_tables.svh directly from the validated golden model.

This exists specifically so the RTL's fixed rho/pi/iota tables are never
hand-transcribed -- transcription of exactly these tables is the top
verification risk flagged in the project plan. Run this, don't hand-edit
the generated file; keccak_f1600.py's own values are cross-checked against
XKCP's published tables in validate_against_xkcp.py before this script
ever runs, so the RTL inherits that same validated source.
"""
from pathlib import Path

from keccak_f1600 import compute_rho_offsets, compute_round_constants

OUT_PATH = Path(__file__).parent.parent / "rtl" / "keccak_tables.svh"


def pi_src_table():
    """PI_SRC[dst] = src lane address, dst/src both 5y+x."""
    table = [0] * 25
    for y in range(5):
        for x in range(5):
            dst = 5 * y + x
            x_src = (x + 3 * y) % 5
            y_src = x
            table[dst] = 5 * y_src + x_src
    return table


def rot_amount_table():
    """ROT_AMOUNT[addr] = rho rotation amount for lane at addr=5y+x."""
    rho = compute_rho_offsets()
    table = [0] * 25
    for y in range(5):
        for x in range(5):
            table[5 * y + x] = rho[x][y]
    return table


def main():
    rot = rot_amount_table()
    pi_src = pi_src_table()
    rc = compute_round_constants()

    # Yosys 0.52's native `read_verilog -sv` frontend rejects unpacked-array
    # syntax outright -- confirmed directly: both an unpacked-array PORT and
    # an unpacked-array LOCALPARAM ('{...} literal) hit a hard syntax error
    # at the declaration itself (see scripts/synth_spike.sh's history in the
    # commit log). Plain functions with a case statement use no array-type
    # syntax at all, which is about as conservatively-synthesizable as SV
    # gets, so that's what's emitted here instead.
    lines = [
        "// AUTO-GENERATED by model/gen_tables.py -- do not hand-edit.",
        "// Source of truth: model/keccak_f1600.py, validated against XKCP",
        "// reference vectors in model/validate_against_xkcp.py before this",
        "// script is trusted to run. Regenerate with:",
        "//   python3 model/gen_tables.py",
        "",
        "// Lane addressing throughout: addr = 5*y + x (see docs/SPEC.md).",
        "// Called only with genvar (elaboration-constant) arguments for rho/pi,",
        "// so these constant-fold to fixed wiring, not a runtime mux -- unlike",
        "// round_constant, which genuinely is a small runtime mux (round_idx",
        "// is a real signal that changes every cycle).",
        "",
        "// Rho: fixed per-lane rotation amount.",
        "function automatic int unsigned rot_amount(input int unsigned addr);",
        "  case (addr)",
    ]
    for addr, amt in enumerate(rot):
        lines.append(f"    {addr:2d}: rot_amount = {amt};")
    lines += [
        "    default: rot_amount = 0;",
        "  endcase",
        "endfunction",
        "",
        "// Pi: fixed lane relabeling. dst lane(addr) <= src lane(pi_src(addr))",
        "function automatic int unsigned pi_src(input int unsigned addr);",
        "  case (addr)",
    ]
    for addr, src in enumerate(pi_src):
        lines.append(f"    {addr:2d}: pi_src = {src};")
    lines += [
        "    default: pi_src = 0;",
        "  endcase",
        "endfunction",
        "",
        "// Iota: round constants, XORed into lane 0 (x=0,y=0) only.",
        "function automatic logic [63:0] round_constant(input int unsigned round_idx);",
        "  case (round_idx)",
    ]
    for r, c in enumerate(rc):
        lines.append(f"    {r:2d}: round_constant = 64'h{c:016X};")
    lines += [
        "    default: round_constant = 64'h0;",
        "  endcase",
        "endfunction",
        "",
    ]

    OUT_PATH.write_text("\n".join(lines))
    print(f"wrote {OUT_PATH} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
