// AUTO-GENERATED by model/gen_tables.py -- do not hand-edit.
// Source of truth: model/keccak_f1600.py, validated against XKCP
// reference vectors in model/validate_against_xkcp.py before this
// script is trusted to run. Regenerate with:
//   python3 model/gen_tables.py

// Lane addressing throughout: addr = 5*y + x (see docs/SPEC.md).
// Called only with genvar (elaboration-constant) arguments for rho/pi,
// so these constant-fold to fixed wiring, not a runtime mux -- unlike
// round_constant, which genuinely is a small runtime mux (round_idx
// is a real signal that changes every cycle).

// Rho: fixed per-lane rotation amount.
function automatic int unsigned rot_amount(input int unsigned addr);
  case (addr)
     0: rot_amount = 0;
     1: rot_amount = 1;
     2: rot_amount = 62;
     3: rot_amount = 28;
     4: rot_amount = 27;
     5: rot_amount = 36;
     6: rot_amount = 44;
     7: rot_amount = 6;
     8: rot_amount = 55;
     9: rot_amount = 20;
    10: rot_amount = 3;
    11: rot_amount = 10;
    12: rot_amount = 43;
    13: rot_amount = 25;
    14: rot_amount = 39;
    15: rot_amount = 41;
    16: rot_amount = 45;
    17: rot_amount = 15;
    18: rot_amount = 21;
    19: rot_amount = 8;
    20: rot_amount = 18;
    21: rot_amount = 2;
    22: rot_amount = 61;
    23: rot_amount = 56;
    24: rot_amount = 14;
    default: rot_amount = 0;
  endcase
endfunction

// Pi: fixed lane relabeling. dst lane(addr) <= src lane(pi_src(addr))
function automatic int unsigned pi_src(input int unsigned addr);
  case (addr)
     0: pi_src = 0;
     1: pi_src = 6;
     2: pi_src = 12;
     3: pi_src = 18;
     4: pi_src = 24;
     5: pi_src = 3;
     6: pi_src = 9;
     7: pi_src = 10;
     8: pi_src = 16;
     9: pi_src = 22;
    10: pi_src = 1;
    11: pi_src = 7;
    12: pi_src = 13;
    13: pi_src = 19;
    14: pi_src = 20;
    15: pi_src = 4;
    16: pi_src = 5;
    17: pi_src = 11;
    18: pi_src = 17;
    19: pi_src = 23;
    20: pi_src = 2;
    21: pi_src = 8;
    22: pi_src = 14;
    23: pi_src = 15;
    24: pi_src = 21;
    default: pi_src = 0;
  endcase
endfunction

// Iota: round constants, XORed into lane 0 (x=0,y=0) only.
function automatic logic [63:0] round_constant(input int unsigned round_idx);
  case (round_idx)
     0: round_constant = 64'h0000000000000001;
     1: round_constant = 64'h0000000000008082;
     2: round_constant = 64'h800000000000808A;
     3: round_constant = 64'h8000000080008000;
     4: round_constant = 64'h000000000000808B;
     5: round_constant = 64'h0000000080000001;
     6: round_constant = 64'h8000000080008081;
     7: round_constant = 64'h8000000000008009;
     8: round_constant = 64'h000000000000008A;
     9: round_constant = 64'h0000000000000088;
    10: round_constant = 64'h0000000080008009;
    11: round_constant = 64'h000000008000000A;
    12: round_constant = 64'h000000008000808B;
    13: round_constant = 64'h800000000000008B;
    14: round_constant = 64'h8000000000008089;
    15: round_constant = 64'h8000000000008003;
    16: round_constant = 64'h8000000000008002;
    17: round_constant = 64'h8000000000000080;
    18: round_constant = 64'h000000000000800A;
    19: round_constant = 64'h800000008000000A;
    20: round_constant = 64'h8000000080008081;
    21: round_constant = 64'h8000000000008080;
    22: round_constant = 64'h0000000080000001;
    23: round_constant = 64'h8000000080008008;
    default: round_constant = 64'h0;
  endcase
endfunction
